#!/usr/bin/env perl
use strict;

# Copyright (c) 2013-2014, Daniel S. Standage <daniel.standage@gmail.com>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# ------------------------------------------------------------------------------
# addmag: add fold change magnitudes to EBSeq output
#
# EBSeq output includes columns for fold change. These values are less than or
# greater than 1 depending on the direction of differential expression. Often it
# is usefule to compare the magnitude of the fold change: the reciprocal of the
# fold change if it is less than 1, and the fold change itself if it is greater
# than 1. This script adds additional columns to the EBSeq output to provide
# this information.
# ------------------------------------------------------------------------------

my $line = <STDIN>;
chomp($line);
$line =~ s/"//g;
$line .= "\tMagPostFC\tMagRealFC\n";
print $line;

while($line = <STDIN>)
{
  $line =~ s/"//g;
  my @fields = split(/\t/, $line);
  my $magpfc = $fields[3];
  my $magrfc = $fields[4];
  if($magpfc < 1)
  {
    $magpfc = 1.0 / $magpfc;
    $magrfc = 1.0 / $magrfc;
  }
  push(@fields, ($magpfc, $magrfc));
  printf("%s". "\t%.4f" x 6 ."\n", @fields);
}
